### ISSUE TITLE
Add all short names (2 characters and below)

### ISSUE THREAD

**Issue by 84** [LabyMod/og-names#14]
No longer possible to create normally, only few hundred exist and even fewer are active so definitely are relevant/rare.

**Comment by Dqnns** [comment]
agreed.

**Comment by LabyStudio** [comment]
I just want to mention that currently the only use case for this database is to give them a badge.
Two character names already have their own badge
https://laby.net/badge/fa886cfe-209c-46eb-ad1f-92d7f0bc979c

Should they get two badges?

**Comment by Dqnns** [comment]
> I just want to mention that currently the only use case for this database is to give them a badge. Two character names already have their own badge https://laby.net/badge/fa886cfe-209c-46eb-ad1f-92d7f0bc979c
> 
> Should they get two badges?

I think every 2 character Name should get a "OG" name tag. ^^

**Comment by orsou** [comment]
> I think every 2 character Name should get a "OG" name tag. ^^

I totally agree! Two character names aren't obtainable anymore which makes them rare/desirable which are key factors for an OG username. **But** I do think adding them in this repositroy is irrelevant since laby.net already has a list of them and there won't be any new additions to the list unlike with the OG names.

**Comment by Dqnns** [comment]
agreed with orsou.

**Comment by 84** [comment]
Fair.
